default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  username: root
  password: 
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: goodjobs_dev

test:
  <<: *default
  database: goodjobs_test

production:
  <<: *default
  database: goodjobs_prod
  host: ENV['mysql_url']
